spring:
  data:
    mongodb:
      username: masrah270
      password: Masroor@16
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

  server:
    port: 8088


